// KEY Localstorage
export const LOCAL_STORAGE = {
  FIREBASE_TOKEN: 'FIREBASE_TOKEN',
  USER_LANGUAGE: 'USER_LANGUAGE',
  USER_INFO: 'USER_INFO',
  USER_TOKEN: 'USER_TOKEN',
  USER_REFRESH_TOKEN: 'USER_REFRESH_TOKEN',
};
